typography_spectrum: 1
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.32749972376041114
  lightness: 0.5808663722127676
  saturation: 0.07891330146230757
  rhythmicContrast: 0.9601052410434932
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.50421
analytics:
  google: null
  facebook: null
  twitter: null
name: thewerk
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: zellwerk
description: Internet Agentur in Düsseldorf und Berlin
purpose: []
